name: Python application

on: [push]
#  schedule:
#    - cron: '23 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: genchin auto check
        run: |
          cd genshin
          sh run.sh

      - name: Commit
        run: |
          git config --global user.email binxiong@126.com
          git config --global user.name xiongbin
          git add .
          #git commit -m"action:`date +'%Y-%m-%d'`"
          git commit -m"action:`date`"
          git pull --rebase

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}